version: "3"
services:
  web:
    image: web:latest
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - backend
    environment:
      SERVICE_NAME: web
    networks:
      network:
        ipv4_address: 192.168.92.21
  backend:
    image: backend:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      SERVICE_NAME: backend
    privileged: true
    volumes:
      - ./sqlite:/sqlite
      - ./videostore:/videostore
    networks:
      network:
        ipv4_address: 192.168.92.22
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
